on: [push]

jobs:
  kafka-sync:
    runs-on: ah-digital-generic
    name: Update app meta information
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Kafka sync
        uses: ./
        id: kafka
        with:
          bootstrap-servers: 10.152.183.181:9094
        env:
          KAFKA_TOPIC_NAME: topic10
          KAFKA_USERNAME: username
          KAFKA_PASSWORD: password
          KAFKA_CA_CONTENT: ${{ secrets.KAFKA_CA_CONTENT }}
